function(azahar_apply_native_runtime_definitions)
    if(TARGET video_core)
        target_compile_definitions(video_core PRIVATE AZAHAR_DEKO3D_STRICT_NATIVE AZAHAR_DEKO3D_NATIVE_RUNTIME)
    endif()
    if(TARGET core)
        target_compile_definitions(core PRIVATE AZAHAR_SWITCH_DYNARMIC_SAFE_OPTIMIZATIONS)
    endif()
endfunction()
cmake_language(DEFER CALL azahar_apply_native_runtime_definitions)
