if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()
if(NOT DEFINED VERT)
    message(FATAL_ERROR "VERT is required")
endif()
if(NOT DEFINED FRAG)
    message(FATAL_ERROR "FRAG is required")
endif()
if(NOT DEFINED TEX_VERT)
    message(FATAL_ERROR "TEX_VERT is required")
endif()
if(NOT DEFINED TEX_FRAG)
    message(FATAL_ERROR "TEX_FRAG is required")
endif()
if(NOT DEFINED PRESENT_VERT)
    message(FATAL_ERROR "PRESENT_VERT is required")
endif()
if(NOT DEFINED PRESENT_FRAG)
    message(FATAL_ERROR "PRESENT_FRAG is required")
endif()

function(read_binary_as_array output_var path)
    file(READ "${path}" hex HEX)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " bytes "${hex}")
    set(${output_var} "${bytes}" PARENT_SCOPE)
endfunction()

read_binary_as_array(VERT_BYTES "${VERT}")
read_binary_as_array(FRAG_BYTES "${FRAG}")
read_binary_as_array(TEX_VERT_BYTES "${TEX_VERT}")
read_binary_as_array(TEX_FRAG_BYTES "${TEX_FRAG}")
read_binary_as_array(PRESENT_VERT_BYTES "${PRESENT_VERT}")
read_binary_as_array(PRESENT_FRAG_BYTES "${PRESENT_FRAG}")

file(WRITE "${OUTPUT}" "#pragma once\n\n")
file(APPEND "${OUTPUT}" "#include <cstddef>\n")
file(APPEND "${OUTPUT}" "#include <cstdint>\n\n")
file(APPEND "${OUTPUT}" "namespace VideoCore::Deko3D::BuiltinShaders {\n\n")
file(APPEND "${OUTPUT}" "inline constexpr std::uint8_t PicaColorVsh[] = { ${VERT_BYTES} };\n")
file(APPEND "${OUTPUT}" "inline constexpr std::size_t PicaColorVshSize = sizeof(PicaColorVsh);\n\n")
file(APPEND "${OUTPUT}" "inline constexpr std::uint8_t PicaColorFsh[] = { ${FRAG_BYTES} };\n")
file(APPEND "${OUTPUT}" "inline constexpr std::size_t PicaColorFshSize = sizeof(PicaColorFsh);\n\n")
file(APPEND "${OUTPUT}" "inline constexpr std::uint8_t PicaTexVsh[] = { ${TEX_VERT_BYTES} };\n")
file(APPEND "${OUTPUT}" "inline constexpr std::size_t PicaTexVshSize = sizeof(PicaTexVsh);\n\n")
file(APPEND "${OUTPUT}" "inline constexpr std::uint8_t PicaTexFsh[] = { ${TEX_FRAG_BYTES} };\n")
file(APPEND "${OUTPUT}" "inline constexpr std::size_t PicaTexFshSize = sizeof(PicaTexFsh);\n\n")
file(APPEND "${OUTPUT}" "inline constexpr std::uint8_t PresentVsh[] = { ${PRESENT_VERT_BYTES} };\n")
file(APPEND "${OUTPUT}" "inline constexpr std::size_t PresentVshSize = sizeof(PresentVsh);\n\n")
file(APPEND "${OUTPUT}" "inline constexpr std::uint8_t PresentFsh[] = { ${PRESENT_FRAG_BYTES} };\n")
file(APPEND "${OUTPUT}" "inline constexpr std::size_t PresentFshSize = sizeof(PresentFsh);\n\n")
file(APPEND "${OUTPUT}" "} // namespace VideoCore::Deko3D::BuiltinShaders\n")
