if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()
if(NOT DEFINED VERT)
    message(FATAL_ERROR "VERT is required")
endif()
if(NOT DEFINED FRAG)
    message(FATAL_ERROR "FRAG is required")
endif()

function(read_binary_as_array output_var path)
    file(READ "${path}" hex HEX)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " bytes "${hex}")
    set(${output_var} "${bytes}" PARENT_SCOPE)
endfunction()

read_binary_as_array(VERT_BYTES "${VERT}")
read_binary_as_array(FRAG_BYTES "${FRAG}")

file(WRITE "${OUTPUT}" "#pragma once\n\n")
file(APPEND "${OUTPUT}" "#include <cstddef>\n")
file(APPEND "${OUTPUT}" "#include <cstdint>\n\n")
file(APPEND "${OUTPUT}" "namespace VideoCore::Deko3D::BuiltinShaders {\n\n")
file(APPEND "${OUTPUT}" "inline constexpr std::uint8_t PicaColorVsh[] = { ${VERT_BYTES} };\n")
file(APPEND "${OUTPUT}" "inline constexpr std::size_t PicaColorVshSize = sizeof(PicaColorVsh);\n\n")
file(APPEND "${OUTPUT}" "inline constexpr std::uint8_t PicaColorFsh[] = { ${FRAG_BYTES} };\n")
file(APPEND "${OUTPUT}" "inline constexpr std::size_t PicaColorFshSize = sizeof(PicaColorFsh);\n\n")
file(APPEND "${OUTPUT}" "} // namespace VideoCore::Deko3D::BuiltinShaders\n")
